### ISSUE TITLE
[BUG] Swiperjs within pane

### ISSUE THREAD

**Issue by ShoppasGit** [roman-rr/cupertino-pane#209]
**Describe the bug**
When I place a swiperjs component in a cupertino pane and I swipe horizontally to change slides I get the following error. Iv tried stoping propagation from the swiper to the pane but with no luck. The cupertino pane still functions vertically as expected just with alot of the same error.

ERROR TypeError: Cannot read properties of undefined (reading 'clientY')
    at Events.getEventClientYX (cupertino-pane.esm.min.js:13:13875)
    at Events.touchMove (cupertino-pane.esm.min.js:13:6647)
    at Events.touchMoveCb (cupertino-pane.esm.min.js:13:3358)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25881:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25881:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26182:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)

**To Reproduce**
Place swiperjs component within cupertino pane.

**Expected behavior**
Someway for me to stop the listeners maybe?

**Comment by roman-rr** [comment]
@ShoppasGit Try to add `events-prefix="swiper-"` to your swiperjs configuration.

```html
<swiper-container events-prefix="swiper-">
            <swiper-slide>Slide 1</swiper-slide>
            <swiper-slide>Slide 2</swiper-slide>
            <swiper-slide>Slide 3</swiper-slide>
</swiper-container>
```

**Comment by ShoppasGit** [comment]
Man you're good!
